# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.widget_17 = QtWidgets.QWidget(self.centralwidget)
        self.widget_17.setGeometry(QtCore.QRect(20, 60, 421, 261))
        self.widget_17.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"background-color: rgb(113, 113, 113);")
        self.widget_17.setObjectName("widget_17")
        self.widget_18 = QtWidgets.QWidget(self.widget_17)
        self.widget_18.setGeometry(QtCore.QRect(10, 10, 401, 241))
        self.widget_18.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_18.setObjectName("widget_18")


        self.verticalLayoutWidget_26 = QtWidgets.QWidget(self.widget_18)
        self.verticalLayoutWidget_26.setGeometry(QtCore.QRect(10, 0, 381, 231))
        self.verticalLayoutWidget_26.setObjectName("verticalLayoutWidget_26")

        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_26)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")

        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(50)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")

        self.label_33 = QtWidgets.QLabel(self.verticalLayoutWidget_26)
        self.label_33.setMinimumSize(QtCore.QSize(180, 0))
        self.label_33.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("D:/Downloads/55.png"))
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_17.addWidget(self.label_33)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setSpacing(4)
        self.verticalLayout_31.setObjectName("verticalLayout_31")

        self.spinBox_11 = QtWidgets.QSpinBox(self.verticalLayoutWidget_26)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setItalic(True)
        self.spinBox_11.setFont(font)
        self.spinBox_11.setMaximum(1000000000)
        self.spinBox_11.setObjectName("spinBox_11")
        self.verticalLayout_31.addWidget(self.spinBox_11)


        self.spinBox_10 = QtWidgets.QSpinBox(self.verticalLayoutWidget_26)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        self.spinBox_10.setFont(font)
        self.spinBox_10.setMaximum(1000000000)
        self.spinBox_10.setObjectName("spinBox_10")
        self.verticalLayout_31.addWidget(self.spinBox_10)

        self.spinBox_8 = QtWidgets.QSpinBox(self.verticalLayoutWidget_26)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        self.spinBox_8.setFont(font)
        self.spinBox_8.setMaximum(1000000000)
        self.spinBox_8.setObjectName("spinBox_8")


        self.verticalLayout_31.addWidget(self.spinBox_8)
        self.horizontalLayout_17.addLayout(self.verticalLayout_31)
        self.verticalLayout_30.addLayout(self.horizontalLayout_17)

        self.pushButton_14 = QtWidgets.QPushButton(self.verticalLayoutWidget_26)
        self.pushButton_14.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_14.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_14.setObjectName("pushButton_14")

        self.pushButton_14.clicked.connect(self.Zakon_Niot)

        self.verticalLayout_30.addWidget(self.pushButton_14)
        self.widget_41 = QtWidgets.QWidget(self.verticalLayoutWidget_26)
        self.widget_41.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_41.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.widget_41.setObjectName("widget_41")
        self.label_11 = QtWidgets.QLabel(self.widget_41)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 180, 81))
        self.label_11.setMinimumSize(QtCore.QSize(180, 0))
        self.label_11.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_30.addWidget(self.widget_41)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def Zakon_Niot(self):
        print("F")
        N_a = self.spinBox_11.value()
        N_m = self.spinBox_10.value()
        N_F = self.spinBox_8.value()
        if (N_a == 0) and (N_m > 0) and (N_F > 0):
            self.label_11.setText(f'')
        elif (N_m == 0) and (N_a > 0) and (N_F > 0):
            self.label_11.setText(f'')
        elif (N_F == 0) and (N_a > 0) and (N_m > 0):
            self.label_11.setText(
                f'Решение: \n Надо найти F преобразуем формулу\n так: F=m*a \n F={N_a}*{N_m}={N_m * N_a}')
        else:
            self.label_11.setText(f'Решения нет')
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.spinBox_11.setSpecialValueText(_translate("MainWindow", "a"))
        self.spinBox_10.setSpecialValueText(_translate("MainWindow", "m"))
        self.spinBox_8.setSpecialValueText(_translate("MainWindow", "F"))
        self.pushButton_14.setText(_translate("MainWindow", "Ответ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
