# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tip_Math.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TipeMath(object):
    def setupUi(self, TipeMath):
        TipeMath.setObjectName("TipeMath")
        TipeMath.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(TipeMath)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(220, 70, 351, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(10, 10))
        self.pushButton.setMaximumSize(QtCore.QSize(325, 100))
        self.pushButton.setSizeIncrement(QtCore.QSize(1000, 1000))
        self.pushButton.setBaseSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setIconSize(QtCore.QSize(16, 16))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(325, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setMaximumSize(QtCore.QSize(325, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setIconSize(QtCore.QSize(28, 16))
        self.pushButton_3.setAutoRepeatDelay(329)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.setStretch(0, 100)
        self.verticalLayout.setStretch(1, 100)
        self.verticalLayout.setStretch(2, 1000)
        TipeMath.setCentralWidget(self.centralwidget)

        self.retranslateUi(TipeMath)
        QtCore.QMetaObject.connectSlotsByName(TipeMath)

    def retranslateUi(self, TipeMath):
        _translate = QtCore.QCoreApplication.translate
        TipeMath.setWindowTitle(_translate("TipeMath", "MainWindow"))
        self.pushButton.setText(_translate("TipeMath", "Алгебра"))
        self.pushButton_2.setText(_translate("TipeMath", "Геометрия"))
        self.pushButton_3.setText(_translate("TipeMath", "Cправочные \n метериалы"))



