# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mathfiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PhysicsMath(object):
    def setupUi(self, PhysicsMath):
        PhysicsMath.setObjectName("PhysicsMath")
        PhysicsMath.resize(1055, 800)
        PhysicsMath.setMouseTracking(False)
        PhysicsMath.setTabletTracking(False)
        PhysicsMath.setAcceptDrops(False)
        PhysicsMath.setAutoFillBackground(False)
        PhysicsMath.setDocumentMode(False)
        PhysicsMath.setDockNestingEnabled(False)
        PhysicsMath.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(PhysicsMath)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 1071, 161))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(240, 200, 491, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setContentsMargins(50, 20, 50, 20)
        self.verticalLayout.setSpacing(50)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        PhysicsMath.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PhysicsMath)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 21))
        self.menubar.setObjectName("menubar")
        PhysicsMath.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PhysicsMath)
        self.statusbar.setObjectName("statusbar")
        PhysicsMath.setStatusBar(self.statusbar)

        self.retranslateUi(PhysicsMath)
        QtCore.QMetaObject.connectSlotsByName(PhysicsMath)

    def retranslateUi(self, PhysicsMath):
        _translate = QtCore.QCoreApplication.translate
        PhysicsMath.setWindowTitle(_translate("PhysicsMath", "Physics_Math"))
        self.label.setText(_translate("PhysicsMath", "Решение математических и физических задач"))
        self.pushButton_2.setText(_translate("PhysicsMath", "Математика"))
        self.pushButton_3.setText(_translate("PhysicsMath", "Физика"))



